# Site settings
title: "Pakati"
tagline: "Revolutionary AI Image Generation"
description: "Advanced AI image generation system with regional control, metacognitive orchestration, and breakthrough reference understanding capabilities."
baseurl: ""
url: "https://fullscreen-triangle.github.io"
repository: "fullscreen-triangle/pakati"

# Theme configuration - using minima with custom styling
theme: minima
minima:
  skin: dark

# Search and navigation
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-gist
  - jekyll-include-cache

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Kramdown settings for scientific content
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# Collections for organized content
collections:
  research:
    output: true
    permalink: /research/:name/
  examples:
    output: true  
    permalink: /examples/:name/
  guides:
    output: true
    permalink: /guides/:name/

# Math support
mathjax: true

# Header navigation
header_pages:
  - index.md
  - architecture.md
  - reference_understanding.md
  - fuzzy_logic.md
  - research.md
  - api.md
  - examples.md

# Footer content
footer_content: "Copyright &copy; 2024 Pakati Project. Revolutionary AI Image Generation with Regional Control."

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Call-outs configuration
callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# Enable copy code button
enable_copy_code_button: true

# Mermaid support for diagrams
mermaid:
  version: "9.4.3" 