source "https://rubygems.org"

# GitHub Pages compatibility
gem "github-pages", group: :jekyll_plugins

# Essential plugins
group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-sitemap"  
  gem "jekyll-seo-tag"
  gem "jekyll-paginate"
  gem "jekyll-gist"
  gem "jekyll-include-cache"
end

# Math rendering
gem "kramdown-math-katex"

# Development dependencies
group :development do
  gem "webrick"
end

# Windows specific
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Performance booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin] 